spring.application.name=answers
spring.profiles.active=${PROFILE_ANSWERS:dev}
server.servlet.context-path=/myanswers

spring.servlet.multipart.max-file-size=50000KB
spring.servlet.multipart.max-request-size=50000KB


spring.cache.type=caffeine
spring.cache.cache-names=answersPaged
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=24h