spring.datasource.url=${PRD_ANSWERDB_URL}
spring.datasource.username=${PRD_ANSWERDB_USERNAME}
spring.datasource.password=${PRD_ANSWERDB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.sql.init.mode=never